version: '3'

services:
  poetry-api:
    build: .
    container_name: poetry-api
    ports:
      - "3030:3030"
    volumes:
      - ../source:/app/data/source
    environment:
      - NODE_ENV=production
      - PORT=3030
      - DATA_DIR=/app/data/source
    restart: unless-stopped
